# Generated by Django 4.1 on 2022-08-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDespesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_despesa', models.CharField(max_length=50, verbose_name='Despesa')),
                ('quantidade_despesa', models.CharField(max_length=50, verbose_name='Qntd.')),
                ('custo', models.IntegerField(verbose_name='Custo')),
                ('tipo_gasto', models.CharField(max_length=50, verbose_name='Tipo de Gasto')),
                ('data_atualizacao', models.DateTimeField(verbose_name='Data de Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='ListaProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50, verbose_name='Produto')),
                ('quantidade_produto', models.IntegerField(verbose_name='Qntd.')),
                ('custo_venda', models.CharField(max_length=10, verbose_name='Custo/Venda')),
                ('fornecedor', models.CharField(max_length=50, verbose_name='Fornecedor')),
                ('data_adicao', models.DateTimeField(verbose_name='Data de Adição')),
            ],
        ),
    ]
