# Generated by Django 4.1 on 2022-10-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDespesas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_despesa', models.CharField(max_length=50, verbose_name='Despesas')),
                ('quantidade_despesa', models.CharField(max_length=50, verbose_name='Qntd.')),
                ('custo', models.IntegerField(verbose_name='Custo')),
                ('tipo_gasto', models.CharField(choices=[('Semanal', 'Semanal'), ('Mensal', 'Mensal'), ('Esporádico', 'Esporádico')], max_length=50, verbose_name='Tipo de Gasto')),
                ('data_adicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('nota_despesa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ListaProdutos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=50, verbose_name='Produto')),
                ('quantidade_produto', models.IntegerField(verbose_name='Qntd.')),
                ('data_adicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('nota_produto', models.TextField()),
            ],
        ),
    ]
