# Generated by Django 4.1 on 2022-10-10 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadespesas',
            name='data_adicao',
        ),
        migrations.AddField(
            model_name='listadespesas',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 10, 13, 19, 48, 502040, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listadespesas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listaprodutos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
