# Generated by Django 4.1 on 2022-08-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadespesas',
            name='nome_despesa',
            field=models.CharField(max_length=50, verbose_name='Despesas'),
        ),
    ]
