# Generated by Django 4.1 on 2022-09-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_listadespesas_nome_despesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadespesas',
            name='tipo_gasto',
            field=models.CharField(choices=[('Semanal', 'Semanal'), ('Mensal', 'Mensal'), ('Esporádico', 'Esporádico')], max_length=50, verbose_name='Tipo de Gasto'),
        ),
    ]
