# Generated by Django 4.1 on 2022-10-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_listadespesas_data_adicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadespesas',
            name='nota_despesa',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listaprodutos',
            name='nota_produto',
            field=models.TextField(blank=True),
        ),
    ]
