# Generated by Django 4.1 on 2022-09-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_listadespesas_tipo_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadespesas',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='listaprodutos',
            name='data_adicao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição'),
        ),
    ]
