# Generated by Django 4.1 on 2022-09-23 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_listadespesas_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadespesas',
            name='nota_despesa',
            field=models.TextField(default=datetime.datetime(2022, 9, 23, 12, 36, 2, 890128, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listaprodutos',
            name='nota_produto',
            field=models.TextField(default=datetime.datetime(2022, 9, 23, 12, 36, 23, 442303, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
