# Generated by Django 4.1 on 2022-10-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_listadespesas_nota_despesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadespesas',
            name='nota_despesa',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='listaprodutos',
            name='nota_produto',
            field=models.TextField(null=True),
        ),
    ]
