# Generated by Django 4.1 on 2022-10-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_listadespesas_nota_despesa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaprodutos',
            name='custo_venda',
        ),
        migrations.RemoveField(
            model_name='listaprodutos',
            name='fornecedor',
        ),
    ]
