# Generated by Django 4.1 on 2022-10-11 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_listadespesas_nota_despesa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaprodutos',
            name='nota_produto',
        ),
    ]
