# Generated by Django 4.1 on 2022-10-12 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_remove_listaprodutos_nota_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaprodutos',
            name='nota_produto',
            field=models.TextField(default=datetime.datetime(2022, 10, 12, 0, 28, 34, 801825, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
