# Generated by Django 4.1 on 2022-10-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_remove_listaprodutos_custo_venda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadespesas',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
