# Generated by Django 4.1 on 2022-10-26 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_listaprodutos_nota_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadespesas',
            name='nota_despesa',
            field=models.TextField(default=datetime.datetime(2022, 10, 26, 10, 55, 44, 614858, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
