# Generated by Django 4.1 on 2022-10-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_listadespesas_nota_despesa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listadespesas',
            old_name='data_atualizacao',
            new_name='data_adicao_desp',
        ),
        migrations.RenameField(
            model_name='listaprodutos',
            old_name='data_adicao',
            new_name='data_adicao_prod',
        ),
    ]
