# Generated by Django 4.1 on 2022-10-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_rename_data_atualizacao_listadespesas_data_adicao_desp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaprodutos',
            name='nota_produto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
